version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "chain-rebalancer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-154kvl3gi80hj"
s3_prefix = "chain-rebalancer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
